server:
  port: 8080

netty:
  host: 127.0.0.1
  port: 7397

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

# 定位模板的目录
#spring.mvc.view.prefix=classpath:/templates/
# 给返回的页面添加后缀名
#spring.mvc.view.suffix=.html
